# Site settings
title: "Ryan O'Connell's Projects"
author: "Ryan O'Connell"
  name: Ryan OConnell
  email: ryan.oconnell416@gmail.com
description: "Projects I have done"

# Build settings
remote_theme: jekyll/minima
